twig:
    file_name_pattern: '*.twig'
    date:
        format: 'd.m.Y H:i'
    number_format:
        decimal_point: ','
        thousands_separator: '.'

when@test:
    twig:
        strict_variables: true
