version: "3.4"

services:
  cypress:
    image: cypress/included:5.3.0
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=http://nginx
      - DEBUG=cypress:*
    working_dir: /app
    volumes:
      - ../app:/app
