version: "3.8"

services:
  cypress:
    image: cypress/included:5.4.0
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=http://nginx
    ipc: host
    working_dir: /app
    volumes:
      - ../app:/app
    tmpfs:
      - /tmp
