version: "3.8"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - "${PHPMYADMIN_PORT}:80"
    tmpfs:
      - /tmp
    depends_on:
      - mariadb

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elasticsearch
    tmpfs:
      - /tmp

  rector:
    image: rector/rector
    working_dir: /project
    user: "${UID}:${GID}"
    volumes:
      - ../api:/project
    tmpfs:
      - /tmp
