version: "3.8"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - "${PHPMYADMIN_PORT}:80"
    tmpfs:
      - /tmp
    depends_on:
      - mariadb
