#!/usr/bin/env node
const https = require('https')

https.get(`https://hub.docker.com/v2/repositories/${process.argv[2]}/tags/?page_size=1`, (response) => {
  let data = ''

  response.on('data', (chunk) => {
    data += chunk
  })

  response.on('end', () => {
    console.log(JSON.parse(data).results[0].name)
  })
})
