services:
    App\Tests\OpenSearchFixturesHandler:
        arguments:
            $mode: '%env(resolve:OPENSEARCH_MOCK_MODE)%'

    OpenSearch\ClientBuilder:
        calls:
            - [setHandler, ['@App\Tests\OpenSearchFixturesHandler']]
            - [setHosts, [['%env(resolve:OPENSEARCH_URL)%']]]

    OpenSearch\Client:
        factory: ['@OpenSearch\ClientBuilder', build]
        public: true
