services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\OpenSearchMock\:
        resource: '../tests/OpenSearchMock/'

    App\Tests\OpenSearchMock\OpenSearchFixturesHandler:
        bind:
            $mode: '%env(resolve:OPENSEARCH_MOCK_MODE)%'

    OpenSearch\Client:
        factory: ['@App\Tests\OpenSearchMock\OpenSearchFixturesHandler', create]
        arguments:
            -
                base_uri: '%env(resolve:OPENSEARCH_URL)%'
        public: true
