services:
    App\Debug\ApiProfilerSubscriber:
        tags: ['kernel.event_subscriber']

    OpenSearch\Client:
        factory: ['@OpenSearch\SymfonyClientFactory', create]
        arguments:
            -
                base_uri: '%env(resolve:OPENSEARCH_URL)%'
        public: true
