name: security

on:
  schedule:
    - cron: '0 5 */1 * *'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make install
      - name: Check security issues
        run: make test-security
