name: test-integration

on:
  schedule:
    - cron: '0 1 * * 0'

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Install Just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Pulling Docker images
        run: just compose pull
      - name: Pulling Cypress Docker image
        run: just compose -f docker/cypress-open.yml pull
      - name: Building Docker images
        run: just compose build
      - name: Maintain Composer cache
        uses: actions/cache@v4
        with:
          path: api/.cache/composer
          key: composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: composer-
      - name: Maintain pnpm cache
        uses: actions/cache@v4
        with:
          path: app/.cache/node
          key: pnpm-${{ hashFiles('app/pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Install dependencies
        run: just install
      - name: Run test-integration
        run: just test-integration
