name: update

on:
  schedule:
    - cron: '0 2 */1 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update dependencies
        run: make update
      - name: Fix code style
        run: make fix-code-style
      - run: make test
      - run: make test-db
      - run: make test-e2e
      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dependencies
          commit_user_name: Maintenance Bob
          commit_user_email: bob@archlinux.de
          commit_author: Maintenance Bob <bob@archlinux.de>
